version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
#      - service-db
      service-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/mydb?currentSchema=base
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  service-db:
    image: postgres:14.7-alpine
    container_name: service-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_INITDB_ARGS: "--auth-local=md5"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "books_db"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - ./src/main/resources/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db-data:/var/lib/postgresql/data
#      - db-data:/var/lib/postgresql@17/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: